language: node_js
node_js:
  - '9.2'
  - '8.0'

before_script:
 - npm install yarn -g
 - yarn --version

script:
  - yarn test

notifications:
  email:
    recipients:
      - ajarombek95@gmail.com
    on_success: always
    on_failure: always